### ISSUE TITLE
Case study - sports analytics

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#164]
Follow-up to gh-82. The proposed case study by @shaloo is:

_Sports analytics ( I noticed that NumPy was used in data analytics in IPL - a big time cricket tournament($$$) in India and SE Asia. See https://gigadom.in/2018/10/28/introducing-cricpya-python-package-to-analyze-performances-of-cricketrs/ May be similar data can be obtained from other sports that use NumPy for athlete performance analysis or play/game analysis and some quotes from say ESPN(!!!? unless this is not as big a deal as the scientific use cases...) on NumPy usage)._

The tile for it on the front page including an image is already designed in gh-159 and will be merged soon.

**Comment by shaloo** [comment]
Initiated some email conversations with a couple of folks who have published studies on Cricket Analytics (that uses NumPy, Pandas etc.).  Working on the outline in Google docs. Once I have substantial information, will put it together in the Hugo case studies format. Fyi.

**Comment by shaloo** [comment]
Here is the first draft. Haven't heard from some of the paper authors referenced in this case study about details.  So far all this data is based on public info mentioned in Google doc references.

I'm facing some git PR issues (more commits show up older ones, instead of only the ones for this case study - trying to sync up my fork/branch).  Meanwhile here is  sneak peak:

Here is how the tiles page looks with updates:

<img width="903" alt="Screenshot 2020-03-02 at 5 32 56 PM" src="https://user-images.githubusercontent.com/5890484/75674978-387bf700-5cac-11ea-9f11-1d6ec273396f.png">

<img width="997" alt="Screenshot 2020-03-02 at 5 36 00 PM" src="https://user-images.githubusercontent.com/5890484/75675068-64977800-5cac-11ea-9807-92cf632d1b57.png">
<img width="927" alt="Screenshot 2020-03-02 at 5 36 09 PM" src="https://user-images.githubusercontent.com/5890484/75675084-6eb97680-5cac-11ea-85ad-174661e0d6b9.png">
<img width="830" alt="Screenshot 2020-03-02 at 5 36 16 PM" src="https://user-images.githubusercontent.com/5890484/75675092-7547ee00-5cac-11ea-95f8-0459fd9decd7.png">
<img width="882" alt="Screenshot 2020-03-02 at 5 36 22 PM" src="https://user-images.githubusercontent.com/5890484/75675111-7ed15600-5cac-11ea-9770-36de333aa5cb.png">
<img width="912" alt="Screenshot 2020-03-02 at 5 36 29 PM" src="https://user-images.githubusercontent.com/5890484/75675118-809b1980-5cac-11ea-982c-0be9d17493b2.png">
<img width="860" alt="Screenshot 2020-03-02 at 5 36 35 PM" src="https://user-images.githubusercontent.com/5890484/75675122-8264dd00-5cac-11ea-972d-3c5793bdb168.png">

**Comment by rgommers** [comment]
> Haven't heard from some of the paper authors referenced in this case study about details.

Ah that answers one of my questions from the PR, sounds like you contacted them and are waiting for replies.

**Comment by rgommers** [comment]
This was merged, closing. Thanks @shaloo. 

Would still be nice to find a more substantial package/user, but we don't need to keep this issue open for it.
