### ISSUE TITLE
Inconsistency in language selector dropdown visibility

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#169]
Some web pages don’t show the language selector dropdown.

**Comment by joelachance** [comment]
This actually is not a bug. The navbar partial checks if there are translations for a given page, and if there aren't any, it won't render the language dropdown (since there's no other language available for that page). The attached PR comments out the Language dropdown until we're in a better place with translations, per @rgommers

**Comment by rgommers** [comment]
Thanks @joelachance, makes sense.
