### ISSUE TITLE
Signup email form field does not enforce valid email address.

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#283]
Ref to the following field in the bottom right of landing page:

<img width="328" alt="Screenshot 2020-05-24 at 3 34 25 PM" src="https://user-images.githubusercontent.com/5890484/82751380-5604bc80-9dd4-11ea-89fd-4d17e1f318c1.png">

User is allowed to simply press enter without any data input and the message says "Thank you" on pressing enter.  If I enter xyzzy or any non-email data, that seems to be acceptable too - no error or request to enter a valid email id.

**Comment by joelachance** [comment]
@shaloo, excellent point. If I remember correctly, I lazily skipped this as Mailchimp _does_ have validation, and that address never gets recorded.

To your very valid point though, that never gets passed back to the user. We can look more into this one.

**Comment by joelachance** [comment]
I think I'm leaning towards punting on this one. It had been a while since I had looked at Mailchimp, but when the user submits an invalid address, you'll get a new window with the following:

![Screen Shot 2020-05-27 at 7 11 24 AM](https://user-images.githubusercontent.com/3891660/83017812-ecf69200-9fe9-11ea-87f9-7c3cb85f594a.png)

The submission form will always say thank you, but I think I'm ok with that as Mailchimp does validation on our behalf.

@rgommers & @shaloo, if you are alright with this resolution, please close this ticket. Thanks!

**Comment by InessaPawson** [comment]
> when the user submits an invalid address, you'll get a new window with the following:

That doesn’t seem to be the case. However, Mailchimp indeed validates all the submitted e-mail addresses. 

I guess the value in having a valid e-mail address enforced on the front end would be to notify subscribers who accidentally make an error in their e-mail address and prompt them to review it.

**Comment by joelachance** [comment]
> That doesn’t seem to be the case.

Do you not get a new window that looks like the above screenshot?

Right now with the way this was implemented we don't get any response from MailChimp whether or not the email was valid, so we won't know how to notify the user if their email was valid. 

There should be an additional screen from MailChimp when there is a new submission. I just checked and was getting an error screen submitting a test email. @InessaPawson, let me know what you find!

**Comment by InessaPawson** [comment]
> There should be an additional screen from MailChimp when there is a new submission. I just checked and was getting an error screen submitting a test email. @InessaPawson, let me know what you find!

I’ve looked into it further. I don’t get the error screen on Safari only. (I checked the pop-up blocker.) The screen would be enough indeed.

**Comment by joelachance** [comment]
That is a bit strange-- that is all on MailChimp's side, so I would expect it to work in all browsers :(
I felt ok punting this issue given in *most* cases we get an additional input/message from MailChimp.
@InessaPawson, let me know if you have any additional thoughts, otherwise I'm going to suggest closing this ticket.

**Comment by rgommers** [comment]
I think I'm fine with closing. It seems like a bit of a corner case, we have more useful ways we could spend time on improving the website I think.

**Comment by joelachance** [comment]
Closing!

**Comment by InessaPawson** [comment]
@joelachance We could send an email asking to validate the email address given during the registration process, but I’m not sure if that’s the best use of our time. The pop-up form from MailChimp provides a decent solution.

**Comment by joelachance** [comment]
@InessaPawson agreed. Unless there's a way to do it with MailChimp, we'd have to use SendGrid (or some email service) in order to do that, which probably isn't worth our time.
