### ISSUE TITLE
Select a static site generator for the new website

### ISSUE THREAD

**Issue by dashohoxha** [numpy/numpy.org#29]
### Possible options for static site generators:

1. **Jekyll**. This is a well maintained option with 855 Github contributors, with contributions within the last month. Jekyll is written in Ruby, and has a simple CLI interface. Jekyll also has a large directory of themes, although a majority cost money. There are several themes (serif, uBuild, Just The Docs) that are appropriate and free. Most themes are likely responsive for mobile, and that should be a requirement. Jekyll uses a combination of liquid templating and YAML to render HTML, and content is written in Markdown. i18n functionality is not native to Jekyll, but can be added easily.

1. **Hugo**. This is another well maintained option with 554 contributors, with contributions within the last month. Hugo is written in Go, and similar to Jekyll, has a simple to use CLI interface to generate static sites. Again, similar to Jekyll, Hugo has a large directory of themes. These themes appear to be free, unlike some of Jekyll's themes. (Sample landing page theme, docs theme). Hugo uses Jade as its templating language, and content is also written in Markdown. i18n functionality is native to Hugo.

1. **Docusaurus**. Docusaurus is a responsive static site generator made by Facebook. Unlike the previous options, Docusaurus doesn't come with themes, and thus we would not want to use this for our landing page. This is an excellent docs option written in React. Docusaurus natively has support for i18n (via Crowdin, document versioning, and document search.

Both Jekyll and Hugo are excellent options that should be supported into the future and are good choices for NumPy. Docusaurus has several bonus features such as versioning and search that Jekyll and Hugo don't have, but is likely a poor candidate for a landing page - it could be a good option for a high-level docs site later on though.

**Comment by dashohoxha** [comment]
I would prefer Hugo, because it is simpler to install and use compared to Jekyll, it is generally faster, and also supports multiple languages. Its themes are also quite impressive, for example: https://themes.gohugo.io/tags/company/

I would also add that in the last community meeting there seemed to be a general consensus that using Hugo would be more preferable.

**Comment by joelachance** [comment]
I haven't been able to make previous meetings, but am planning to attend the meeting next Wednesday, Aug 14th.

@rgommers @dashohoxha without knowing any additional info than what is in the NEP, is Hugo a go? Also, have themes been discussed? These can be switched pretty easily, so choosing a theme shouldn't be a showstopper.

**Comment by rgommers** [comment]
> I haven't been able to make previous meetings, but am planning to attend the meeting next Wednesday, Aug 14th.

Sounds good! We could also try and do a separate call, because the community call is about many topics. We'll also have @InessaPawson and @Shekharrajak heavily involved. @dashohoxha got a Season of Docs slot with another org (DVC), so not sure he will still be involved.

@InessaPawson has volunteered to coordinate the website redesign, so she may want to set up a poll for a good time for a call? I think we cover at least all US time zones, and India.

**Comment by stefanv** [comment]
W.r.t. the original issue, I'd like to state a preference for a solution that can easily be installed locally.  In my experience, this excludes Jekyll.

**Comment by dashohoxha** [comment]
>  @dashohoxha got a Season of Docs slot with another org (DVC), so not sure he will still be involved.

If you need my opinion on some topic, just call me (by including @dashohoxha on the issue). I find that my previous opinions/suggestions have been mostly refuted or declined, but this does not prevent me to give my opinion whenever needed.

I have already expressed my preference for Hugo.

**Comment by Shekharrajak** [comment]
Here is my research: 

We should have the following features in NumPy Static pages 👍 

**Markdown based:**  So that technical writers don't have to worry about installation. They can write simply in .md file. Anyone can click on edit button shown in website (new feature) and contribute (edit/suggest changes for the page in Github) to make it better. This will engage users to add new content or edit content to improve it.

**Documentation Search:**  User should be having search box, so that they can easily and quickly find out relevant contents. 

**Document Versioning:** User should be able to switch between the old and new versions easily. They should be able to checkout old version details as well.
Localization/Translation:  User may have option to switch between languages. They should be able to read in native language as well.

**New release note and Blogs:**  Website should be updated with new blog posts and news about the current development and roadmap. So kind of blogging should be present in landing page.

**Fast development:**  Most of the SSG (Static Site Generator) frameworks are running in server and changes in file reflects immediately in UI. Also deploy and build process should be easy.
In future, if we want to change the framework, we use. Then it should be easy. Most of the frameworks support Markdown writing so just moving the .md files and few changes should be enough.

Framework should provide flexibility to extend the features or add new features easily. So framework should have plugin system.

**Comment by Shekharrajak** [comment]
I have researched on few popular frameworks. Here is the summary: 

**Jekyll**

- Simple and easy for developers to work on templates and change the UI.
- Easy for Writer to write on Markdown page (or use HTML, CSS in .md file).
- Free hosting with Github.

__Note:__
- Need to setup Ruby environment and install gem, bundler for Jekyll.


**Hugo**

- Fast and simple for developers .
- Uses Markdown so it is easy for writers.
- Multilingual feature (need to explore about it).
- Lot of theme available  officially at https://themes.gohugo.io/
- Free hosting with Github.

__Note:__

- No need to setup the Go language (Hugo is written in Go).
Simple installation.

**Docusaurus**

- Simple and made for documentation only.
- Maintained by Facebook and built using React.
- Markdown for writing.
- Translations using Crowdin
- Document Versioning feature in built. User can see all versions of your project.
- Document Search feature is inbuilt using Algolia. 
- Free hosting with Github using npm.
- Generate Docker related files while creating a project.

__Note:__

- Need to setup node and NPM for installation. 
I personally feel Javascript frameworks have more features because npm have very useful packages.


**Gatsbyjs**

- Fast and built on React.
- Rich data plugin ecosystem and supports Markdown, JSON, CSV different data sources.
- Static PWA (Progressive Web App) generator. So it loads faster.
- Gatsbyjs have large amount of plugins available officially.

__Note:__

Need to setup node and NPM for installation. 

And there are few other popular Static site generators (like: Hexo, NextJS). 

I personally liked Docusaurus, because it is built for documentation only & it is maintained by Facebook having large community. I feel that JavaScript frameworks have bright future in web applications.

Although we still need to think/discuss more on this and choose the correct one as per our requirement.

**Comment by rgommers** [comment]
> W.r.t. the original issue, I'd like to state a preference for a solution that can easily be installed locally. In my experience, this excludes Jekyll.

That's a good point. We didn't consider that point before, and I assumed it would be true for all static site generators. But yes, Ruby gems have been tricky in the past usually.

**Comment by rgommers** [comment]
> is Hugo a go? Also, have themes been discussed? These can be switched pretty easily, so choosing a theme shouldn't be a showstopper.

Hugo does seem the preferred option; most people have used it, everyone is positive about it. 

Themes: no, not discussed as far as I can remember. Any suggestions welcome I'd say.

> Hugo: Multilingual feature (need to explore about it).

that would be nice to check out to confirm that works with something like Crowdin as well.

**Comment by InessaPawson** [comment]
@dashohoxha, thank you for all your input and making yourself available to our team in the future! Diversity of ideas and opinions is vital to the success of any project, especially with such a large and diverse user community as NumPy.

**Comment by InessaPawson** [comment]
After in-depth research and several thoughtful discussions with the NumPy community members, the web team has selected Hugo (gohugo.io) as a framework for the new website.
