### ISSUE TITLE
How to request inclusion in the 'Ecosystem' tab

### ISSUE THREAD

**Issue by gonzalocasas** [numpy/numpy.org#313]
Following up on a [twitter conversation with numpy team](https://twitter.com/ralfgommers/status/1265765616906108934), I would like to know what's the process to request inclusion of an open source project in the 'Ecosystem' tab.

In particular, I am part of the core dev team of [COMPAS framework](https://compas-dev.github.io/), a python framework for research in architecture/engineering/digital fabrication (ie 2D/3D geometry, robotics, structural analysis, etc), but the question is also valid in general for any other project wishing to be featured there.

**Comment by rgommers** [comment]
Thanks for opening this issue and suggesting COMPAS @gonzalocasas.  I'll look in more detail within the next few days.

**Comment by rgommers** [comment]
Okay, not within a few days, 2020 interfered - sorry about that @gonzalocasas.

There's multiple issues about people wanting to add things to the Ecosystem tab. So here's a policy on that, which aims to help us address obvious issues, without introducing too much of a burden (we really don't want too frequent updates on categories in particular, because dealing with icons is going to be time-consuming).

_Goals for this tab are_:
1. Provide an overview that shows the breadth of scientific domains NumPy is used in. It does not aim to be comprehensive (that's impossible), just has to be a nice sampling.
2. For each included domain, highlight up to four packages that are most prominent/interesting/high-quality/large in that domain. This is a judgement call (by the NumPy web team), and easier to change. 

We now have a couple of categories with only one or two entries. We can consider replacing those with other categories. The layout has to remain appealing visually, so let's keep it at two rows of either 7 or 8 entries.

_To propose a change in categories_: open an issue to discuss first. The bar will be high here.

_To propose a change in projects listed under a category_: 
- feel free to open a PR directly.
- If the category is full (i.e. has four items), you will also need to pick the project to be removed. 
- Note that projects included should be actively maintained and in good shape, i.e. we shouldn't have doubts about recommending users to use that package.
- We will typically prefer community-driven open source projects over company-based, academic, and single-author projects.

**Comment by rgommers** [comment]
Proposed new packages and categories so far:
- COMPAS Framework. That would require a fitting category to start with, which would be something like "architecture, 2D/3D geometry, robotics, structural analysis"
- gh-321 proposes to merge the signal and image processing categories
- a proposal in a https://github.com/numpy/numpy.org/issues/320#issuecomment-658979404 to move "Interactive Computing" to a separate tab (so remove the category)
- gh-320 proposes to add a "graphs and networks" category, with projects: NetworkX, graph-tool, PyGSP
- gh-319 proposes to add a "geoscience" category, with projects: Pangeo, (Xarray), Simpeg, ObsPy, and Fatiando a Terra

Candidate categories for removal:
- Cognitive Psychology (only 1 project)
- Symbolic Computing (only 1 project)
- Interactive Computing (because move to tab)
- Simulation Modeling (only 1 project)
- Multi-variate Analysis (only 1 project)

So here's what I'd like to do:
- Add Categories: Graphs and Networks, Geoscience, Robotics
- Add Interactive Computing as a tab
- Remove categories: Interactive Computing, Simulation Modeling, Symbolic Computing
- Rename "Multi-variate Analysis" to Chemistry and update projects (e.g. Cantera, something significant listed at https://github.com/lmmentel/awesome-python-chemistry). PyChem doesn't seem maintained so shouldn't be listed it looks like.
- Keep signal and image processing separate. They're kind of separate communities and there's projects to list for both. I don't really care the math that it's based on is basically the same.
- Keep Cognitive Psychology - only one entry now, but it broadens the span of domains.

**Comment by brgcode** [comment]
hi @rgommers

very cool that you are considering to add COMPAS to the Ecosystem tab of Numpy!

considering that COMPAS is "_a framework for research and collaboration in Architecture, Engineering, Fabrication and Construction_" would it be at all possible to add a category that is broader than "Robotics" (assuming that this is what you had in mind for COMPAS)?

something like "Architecture and Engineering" perhaps?

**Comment by rgommers** [comment]
I can't think of any other architecture projects, while I could find multiple robotics ones. So maybe something like _"Robotics and Construction"_?

**Comment by brgcode** [comment]
okay, fair enough...
perhaps this can be changed in the future when there are other similar projects within that scope?

**Comment by gonzalocasas** [comment]
There's quite a few architecture projects using numpy, here's a quick list: [sverchok](https://github.com/nortikin/sverchok), [IfcOpenShell](https://github.com/IfcOpenShell/IfcOpenShell), [CityEnergyAnalyst](https://github.com/architecture-building-systems/CityEnergyAnalyst), [UrbanPy](https://github.com/EL-BID/urbanpy), [FEniCS](https://bitbucket.org/fenics-project/), [geomdl/NURBS-Python](https://github.com/orbingol/NURBS-Python), and there's more listed in the [directories on OSArch](https://wiki.osarch.org/index.php?title=Home_of_OSArch)

**Comment by rgommers** [comment]
Thanks @gonzalocasas. Sverchok and CityEnergyAnalyst in particular look good. UrbanPy seems very small, and I think FEniCS and NURBS-Python aren't really architecture tools (more like general-purpose PDE solver and spline toolbox).

Now I'm not sure anymore if Robotics or Architecture is better. Any other opinions?

**Comment by brgcode** [comment]
"architecture" can perhaps be an umbrella category for "digital/robotic fabrication", "construction", "engineering", ... until there are enough projects for one of those sub-categories to be split off?

"robotics" is an entire field by itself. in my opinion, COMPAS doesn't really fit there, since its robotic components are quite specifically related to robotic fabrication (in architecture)

**Comment by rgommers** [comment]
Architecture sounds much more narrow than engineering, but the rest makes sense to me. @numpy/numpy-web-team any objections to going with Architecture?

> until there are enough projects for one of those sub-categories to be split off?

I'm not in a hurry with that, given the maintenance effort (e.g. remaking icon in a uniform style) - the goal is not to be comprehensive, but give a nice overview of the breadth of application domains and highlight prominent projects in the areas we pick.

**Comment by shaloo** [comment]
How about 'Design' or 'Automation'  - both are broader than arch imho.

**Comment by brgcode** [comment]
sorry to keep nagging about this, but, in my opinion, "Design" is too non-specific and, at least for COMPAS, "Automation" is completely unrelated.

> I'm not in a hurry with that, given the maintenance effort (e.g. remaking icon in a uniform style) - the goal is not to be comprehensive, but give a nice overview of the breadth of application domains and highlight prominent projects in the areas we pick.

how about "Architecture & Engineering" then? for COMPAS this is entirely appropriate, and i can imagine that the people from, for example, sverchok, CityEnergyAnalyst, UrbanPy, ... would not mind it either...

**Comment by rgommers** [comment]
Renamed to _Architecture & Engineering_ and added links:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/98330/113623127-3417cf80-965e-11eb-97dc-0defe7713efe.png">

**Comment by rgommers** [comment]
Thanks for the input everyone.
