### ISSUE TITLE
Color scheme for new site

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#33]
From Summer, our graphic designer at Quansight, a color scheme for the new website. Top row are primary colors, second row secondary, third row tertiary. To go with the Hugo Fresh theme that we aimed for as a base. This is the same color scheme as I put on Slack earlier, copying here for permanent storage. This seems like a good start, let's see how it looks:)

![colorscheme_numpyorg_redesign](https://user-images.githubusercontent.com/98330/63642399-51f41480-c673-11e9-8d22-20315b71c83e.jpg)

**Comment by shoyer** [comment]
Looks very nice!

If someone wants to refresh the colors on the NumPy logo, that would also be very welcome in my opinion. The current design looks a little faded.

**Comment by rgommers** [comment]
> If someone wants to refresh the colors on the NumPy logo, that would also be very welcome in my opinion. The current design looks a little faded.

Good point. @InessaPawson's suggested the same last week - I've asked Summer to have a go at that as well.

**Comment by rgommers** [comment]
There was a follow up to this where @InessaPawson posted a much more subtle color palette with several shades of blue, the ones she used in her slide template as well. I just can't find it anywhere currently.

**Comment by InessaPawson** [comment]
@rgommers Here is the color scheme for the new website.

**PRIMARY COLORS**
#ffc553
#4dabcf
#4d77cf

<img width="864" src="https://user-images.githubusercontent.com/43481325/77906035-99f2ae00-72ca-11ea-9d3d-c0106767b44b.png">

**SECONDARY COLORS**
#ffffff
#013243
#eeeeee
#6c7a89

<img width="1110" src="https://user-images.githubusercontent.com/43481325/77906043-9ced9e80-72ca-11ea-9809-1e0eb396aabb.png">

**Comment by sm-Fifteen** [comment]
Are these color codes relative meant to be used with an sRGB color space? There's no color profile data in the SVG logo and the SVG specification says to assume sRGB by default, so it likely is the case, but the values I'm getting looking up the names of each color are slightly different from the listed ones (though the names could be arbitrary) so I have some doubts. This isn't *critical* in most cases, but with branding it's often important to specify color-space so that the colors can be made consistent across various devices and print.

Those color codes are 3D coordinates in an RGB color space, after all, with that color space itself being defined as a polyhedron with curved faces in a different 3D space of perceived chromaticity and luminance, so the hexadecimal color codes on their own technically don't represent a specific color unless that color space is known.

It's not just an abstract issue either, the same color codes in, say, Photoshop (which I believe uses `a98-rgb` by default) won't give you the same colors as they do in CSS.

**Comment by joelachance** [comment]
Hi @sm-Fifteen! Thanks for posting.

I don't think there was any discussion around using these in the sRGB color space. It seems like you likely know more about this topic than myself (I'm assuming others here as well), if you have improvements we can make, please contribute!

**Comment by sm-Fifteen** [comment]
It's really just that codes like `#FFC553` don't actually describe colors, it's just an 8 bit hexadecimal representation of a 3D vector meant to be interpreted as RGB, so it's just an alternative way of writing `(255/255, 197/255, 83/255)` or (approximately) `(1.00, 0.77, 0.33)`. Since these are just vector components, you can't really make sense of them unless you know (basically) what red, what green and what blue (and white point and black point) these components are to be applied, which is all information that a color profile encodes.

On the internet (until [CSS-color-4](https://www.w3.org/TR/css-color-4/#icc-colors) gets implemented anywhere), all colors are assumed to be sRGB (which was designed for VGA CRTs in the 1990s, so it isn't terrific in the age of 10 bit HDR LCD monitors, but it does the job well enough for most people) except for images that embed color profile information, and the same goes for SVGs that don't specify any color profile. Adding an "All RGB colors are specified in the sRGB color space" note or similar to the branding document wouldn't affect the look of anything, it would just clarify how the color coordinates are meant to be interpreted.

**Comment by InessaPawson** [comment]
@sm-Fifteen Thank you for your input! Yes, all the RGB colors are in sRGB. Since it has been the default color space for the past 20 years, graphic designers rarely specify it. However, defaults can and do change over time. I’ll update my comment and also ask Isabela @isabela-pf, the graphic designer who worked on the NumPy logo redesign, to add this info to all the files pertaining to the new logo.
