### ISSUE TITLE
Stale version of docs at Read The Docs

### ISSUE THREAD

**Issue by chrish42** [numpy/numpy.org#431]
Hi. This seemed like the best place to file this issue. There's a stale version of the numpy docs at https://numpy.readthedocs.io/en/latest/.

I feel either deleting it or setting up a redirect to numpy.org/doc would be more than good enough. Either would avoid people using a version of the docs that's not updated anymore, at least.

**Comment by rgommers** [comment]
Thanks for the report @chrish42.

@shoyer the RTD setup was pointing at your fork rather than the main repo. I changed that now. 

I don't want to delete the whole project, because then someone else can take over the `numpy` name on RTD I think. But we also don't want to maintain it. Anyone know of any solutions? @astrojuanlu maybe?

**Comment by shoyer** [comment]
I asked over in the RTD support issues: https://github.com/readthedocs/readthedocs.org/issues/8143

**Comment by astrojuanlu** [comment]
Hah, I was writing a response at the same time you opened the issue upstream :) let's continue the discussion there

**Comment by InessaPawson** [comment]
RTD doesn’t seem to offer new solutions for taking care of this issue. Should we add an index as suggested here: https://github.com/readthedocs/readthedocs.org/issues/8143#issuecomment-829107703?

**Comment by mattip** [comment]
According to the [numpy project page](https://readthedocs.org/projects/numpy/) the maintainers on ReadTheDocs are @rgommers, @shoyer, and @WoLpH. If someone else wants to pick this up, one of the maintainers will need to give them the needed permissions. Any volunteers?

**Comment by WoLpH** [comment]
I can give permission, just tell me the username. I only created the project on read the docs many years ago in the hopes of having up to date docs available. But I couldn't get it to build at that time.

 I'm not sure about the current state though.

**Comment by shoyer** [comment]
If someone wants to do something with this page, I am happy to share
permissions. But I don't think it's really worth worrying about, unless we
hear reports from users who are surprised by it. I don't see the
ReadTheDocs page showing up when I search for the NumPy docs in Google.

**Comment by WoLpH** [comment]
How about a little stub documentation that (automatically) redirects you to the numpy docs?

**Comment by shoyer** [comment]
that sounds fine, if someone wants to put that together

**Comment by shaloo** [comment]
I can take that up.  Can you give me permissions on RTD so that I can create a stub that redirects to official NumPy docs page?

**Comment by rgommers** [comment]
Thanks @shaloo! Is your ReadTheDocs username also `shaloo`? If you don't have an account there yet, you'll need to create one.

**Comment by shaloo** [comment]
@rgommers, @mattip here is the draft setup at RTD - please take a look and let me know if there are any suggestions.  I have used the default RTD theme, easier to setup/build and deploy for a single page redirect. https://numpy.readthedocs.io/en/latest/

Also, for now I have used a public git repo (https://github.com/shaloo/numpydoc-redirect) that RTD points to in order to generate this page.  If you'd like me to keep it under NumPy - or transfer it as a sub project of NumPy, pls guide on how to move it / access etc.

**Comment by rgommers** [comment]
That looks great, thanks @shaloo!

> Also, for now I have used a public git repo (https://github.com/shaloo/numpydoc-redirect) that RTD points to in order to generate this page. If you'd like me to keep it under NumPy - or transfer it as a sub project of NumPy, pls guide on how to move it / access etc.

It's probably a good idea to transfer that repo indeed. Hopefully we'll never have to update it, but I can image that we'd want to in the far future, and that we then can't find the link anymore.

If you go to https://github.com/shaloo/numpydoc-redirect/settings, then at the bottom of that page you should see "Transfer ownership". If that doesn't work because you don't have enough permissions on the NumPy org, can you give me admin rights on your repo (use "Manage access" in Settings)? Then I can move it.

**Comment by shaloo** [comment]
I tried to transfer ownership but it did not allow me to do move it to NumPy.org. Adding @rgommers as admin to do the needful.

**Comment by rgommers** [comment]
Ah, that wasn't quite enough @shaloo - it needs to be Admin permissions, not Write or Maintain.

**Comment by shaloo** [comment]
I do not see any option for 'Role' or editing permissions.  When I added you as a collaborator to the repo - it just sent the default invite - I am not sure how to add you as an admin - looked around in settings but can't seem to find any option.  Let me try transferring the repo to you as a user and not NumPy.org<img width="1187" alt="Screenshot 2022-01-01 at 4 29 56 PM" src="https://user-images.githubusercontent.com/5890484/147849123-0a5e8b1d-934f-41be-b679-4e4f88bfa5ea.png">

**Comment by shaloo** [comment]
Transferred to @rgommers.  Can you access it now?

**Comment by rgommers** [comment]
Done: https://github.com/numpy/numpy-readthedocs-redirect

Thanks @shaloo! I think we're good here, let's close this issue.

**Comment by shaloo** [comment]
After moving NumPy-readthedocs-redirect, we also need to update RTD Repository URL from 

```
https://github.com/shaloo/numpydoc-redirect.git

```

to 
```
https://github.com/numpy/numpy-readthedocs-redirect
```

Done, now :-)
