### ISSUE TITLE
Flip the navbar buttons "About us" and "Contribute"

### ISSUE THREAD

**Issue by Uttam-Singhh** [numpy/numpy.org#440]
According to convention `"About us"` button always comes at the last of a Navbar.
so flip `"About us"  button `with `"Contribute"`.

![1](https://user-images.githubusercontent.com/63050765/120076254-3dec0b00-c0c2-11eb-81c2-2c21781447d6.JPG)

I'd love to work on this and solve this.
Please give me a green signal and assign me this task.

**Comment by Uttam-Singhh** [comment]
Can I work on this @rgommers??

**Comment by rgommers** [comment]
That makes sense I think. There's a lot of discussion on site layout at https://github.com/numpy/numpy.org/issues/43#issuecomment-533544857, but I cannot remember or see a specific comment on order of `About us` and `Contribute`. Cc @InessaPawson, who I think designed this order.

> Can I work on this @rgommers?

You can submit a PR if you want, but I'd like to wait for @InessaPawson's input before merging it.

Also note that we have two translations, Brazilian and Japanese. If you swap the order in English, please make sure to also swap the other two languages (should be done in `content/LANGUAGE/config.yaml`).

**Comment by Uttam-Singhh** [comment]
Oh ok, sure I will do it for all the languages!
I will actually wait for @InessaPawson also to give her input on this idea before I start working!

**Comment by rkern** [comment]
I don't know that there's a particular convention that puts the "About Us" all the way on the right, at least in the context of our other design choices. Because our header is right-aligned, the last item on the right is where you want to put the "call to action" items, and "Contribute" is the main one for us (why? [Corners are easier to hit](https://en.wikipedia.org/wiki/Fitts%27s_law#Implications_for_UI_design).). "About Us" is the kind of item I'd want to "bury" in the middle. It's something that people should be able to navigate to at their leisure, but it isn't a call to action.

Now, if our header were left-aligned, I'd make the "Contribute" its own button in the top-right corner separate from the other header items, and indeed, "About Us" would be the right-most item from the left-aligned header.

**Comment by InessaPawson** [comment]
I appreciate your enthusiasm, @Uttam-Singhh! To echo @rkern, in modern UI/UX design, there is no convention on what buttons should be placed in the top navigation bar and in what order. These choices are determined by objectives and priorities of a project. And as you can tell by reading this thread https://github.com/numpy/numpy.org/issues/43#issuecomment-533544857, we have given a lot of thought to it. I believe the current top menu is optimal to meet the needs of all NumPy stakeholders.

**Comment by Uttam-Singhh** [comment]
Oh ok, Thank you @InessaPawson for clearing this out!
Closing this issue!
