### ISSUE TITLE
Problems with the interactive terminal on the main page

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy.org#466]
The interactive terminal on the main page has never really worked that well for me. Specifically:
 - It can take a long time for the terminal instance to instantiate once the "enable" button has been clicked. I typically experience load times ~10 sec, but I've also experienced times in the 30s-1min range.
 - Once the terminal is live, it opens (for me) with a blank line and there is no indication (e.g. a flashing cursor) that it is ready for input
 - Acquiring the focus of the terminal is difficult - I would expect that clicking anywhere in the terminal box would enable typing in it, but IME it only works if you click on the first "row" in the terminal box. In addition - the first time you click on the first "row", it auto-populates with `import numpy as np`. Having this be the first line makes sense, but it's strange that it doesn't show up until you acquire the focus of the terminal
 - There is no history/output in the terminal, and no other indication that a command has been run. The terminal only displays output for a single command, and for commands that don't result in any ouput, there's no other indication that it ran at all. For example, if you run the first `import numpy as np` command, it remains on the input line and there is no output. In order to enter a new command, you have to manually delete the first line once it's been run. Similarly, any command that doesn't have output (e.g. `a = np.arange(10)`) has the same pattern: the command remains on the input line until it's manually deleted, and there is no indication that the command actually ran.

I realize that a lot of this may be browser-specific (I'm on Firefox) or related to the external services (e.g. Binder), but I thought it'd be worth reporting here.

**Comment by rgommers** [comment]
Some of this is known I think, but some items may be fixable - any thoughts on this @joelachance?

**Comment by joelachance** [comment]
Thanks for the report @rossbar! Unfortunately I think most of the things you're seeing are more or less expected.

1. This is Binder loading. There's no way around this one.
2. I think this is how Thebelab works. We'd have to implement something custom to do this.
3. I don't think Thebelab works this way, but maybe it's been updated.
4. Yep, no history. Again, I think this is Thebelab. I believe we had a spinner on the button to indicate a process was executing, but I don't remember. 

Some history:
This is built using [Thebe](https://github.com/executablebooks/thebe) and a bunch of custom hacks to make it look a little nicer. Maybe everyone agrees Thebelab is better without optimizations and some of those can be removed, although I don't think any of them are causing the issues in this ticket. Thebe has also likely updated since this was implemented, and some of the things you're finding might now be supported.
This definitely isn't anywhere close to an IDE you might use on your computer, so I think with any tool it's going to be difficult to achieve that. There might be newer tools that we didn't know about when this was implemented, so another look at things is probably worth while.

**Comment by jarrodmillman** [comment]
See #547.
