### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by jarrodmillman** [numpy/numpy.org#473]
Should we rename the default branch `main` from `master`?  Many other repositories have done it already including `numpy/numpy`.  This should just involve clicking a button in the settings and then doing a global search and replace to update internal references to the old name.

**Comment by rgommers** [comment]
Yes we should, but not now. We did not touch this repo on purpose, because there's website deployment changes involved. CloudFlare (hosting), Netlify (preview), the separate deployment repo (https://github.com/numpy/numpy.github.com) etc. are not fun to deal with.

Last time we touched that it cost me more than half a day to fix things. This is more a Christmas-time change, when there's time to deal with the likely fallout.
