### ISSUE TITLE
Sunsetting the Google Analytics services

### ISSUE THREAD

**Issue by jarrodmillman** [numpy/numpy.org#550]
Per the discussion in #546, we are temporarily trying both google analytics and plausible.  Once we decide whether to use google analytics or plausible, we will need to either:

## Remove google analytics (see #549)

Remove the following files
```
layouts/_default/baseof.html
layouts/partials/meta.html
```
as well as this line
```
googleAnalytics: UA-162151853-1
```
in `config.yaml.in`.

## Remove plausible analytics (see #546)

Remove
```
  plausible:
    dataDomain: numpy.org
```
from  `config.yaml.in` and
```
## Analytics

A self-hosted version of [Plausible.io](https://plausible.io) is used to gather simple
and privacy-friendly analytics for the site. The dashboard can be accessed
[here](https://views.scientific-python.org/numpy.org).
```
from `README.md`.

## Why use plausible?

The theme will only support plausible going forward, so using it will involve less customization for numpy.org.  For more information, see https://plausible.io/vs-google-analytics.

**Comment by rgommers** [comment]
I don't think there's a real decision point here between the two. We know we want privacy-friendly data from Plausible, we just don't want a gap in data. As soon as Plausible is working well and we have similar quality data to what we now get from Google Analytics, then we can drop Google Analytics.

**Comment by rgommers** [comment]
Thanks for finishing this @jarrodmillman!

Now that we have switched to only Plausible, it would be good to post the current data of both Google Analytics and Plausible, so we have a data point showing how the visitor numbers compare. That way we can normalize future numbers, otherwise we're probably going to see them as a drop in visitor numbers.

Here is the Google Analytics data as of right now:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/98330/183384829-5b427f93-b135-4c13-bc08-d2091934cb08.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/98330/183384448-d166e3b0-e860-43c6-b30a-ecc32cce4e39.png">

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/98330/183384665-57111724-ae97-4d60-b742-ecc3efb30a2d.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/98330/183384929-4121f4d8-9493-451d-8bbc-6b302cf493ea.png">

<img width="501" alt="image" src="https://user-images.githubusercontent.com/98330/183385167-8e697886-f4ef-438c-8eea-2ecd2a1d69ae.png">

Now ~150,000 users/month vs. ~100,000 a year and a half ago (see https://github.com/numpy/numpy.org/issues/269#issuecomment-668271981) seems about right. As noted in that discussion, the Cloudflare numbers are way higher, more like ~2,000,000/month.

**Comment by rgommers** [comment]
@jarrodmillman can you post what you're seeing from Plausible?
