### ISSUE TITLE
Cross platform and browser testing for Hugo generated pages

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy.org#57]
The website should work entirely in the last few versions of the most popular platforms (macOS, Linux, Windows, Android, iOS) and browsers (Chrome, Opera, Firefox, IE/Edge, Safari), and provide an acceptable experience on IE 8 and 9. It must be WCAG AA compliant.

**Comment by MarsBarLee** [comment]
Could I take a stab at this? I'll incorporate the [test site Joe suggested](https://www.lambdatest.com/). I don't have much experience making something WCAG compliant besides alt text for images but I can look into that as well.

**Comment by joelachance** [comment]
Of course! Curious how it goes/what you find.

**Comment by MarsBarLee** [comment]
Quick update: most issues I've seen so far are related to screen/device size, rather than operating system or browser. In many mobile devices the footer is missing, the navigation bar icon is repeating twice and clipping itself or too much white space. I'll look into CSS media queries and start on that tomorrow.
