### ISSUE TITLE
replace the Twitter logo in the footer of numpy.org with X logo

### ISSUE THREAD

**Issue by partev** [numpy/numpy.org#765]
![Screenshot 2024-07-21 10 47 16](https://github.com/user-attachments/assets/9a20f52e-702e-4516-9289-58f453c245aa)

**Comment by mattip** [comment]
I think we should remove the link to X (twitter). We don’t really use that media anymore.

**Comment by InessaPawson** [comment]
@mattip We actually do, for announcements only. Besides the NumPy mailing list, LinkedIn and X are our common channels for communication with wider NumPy dev and user communities.

**Comment by mattip** [comment]
That is a shame, X is such a toxic environment. Maybe LinkedIn is enough.

**Comment by rossbar** [comment]
I know it isn't the proper forum for decision-making, but I agree with @mattip - I'd +1 with removing the link rather than updating the logo

**Comment by InessaPawson** [comment]
@rossbar @mattip @melissawm I will put it as a topic on the meeting agenda for the next community call on July 31st.

**Comment by InessaPawson** [comment]
After discussing the issue at this week’s community call, we agreed to keep the project’s existing accounts on LinkedIn and X for announcements only (as before) but remove the links from numpy.org. This decision is motivated by the fact that the primary goal of these social media accounts is to direct traffic to the website, rather than to expand our social media audience.

**Comment by partev** [comment]
closing per last comment
