### ISSUE TITLE
Add a scroll down arrow to the 'above the fold' section

### ISSUE THREAD

**Issue by joelachance** [numpy/numpy.org#85]
Add an arrow at the bottom of the 'above the fold' section of the homepage to indicate to the user there is more content.

**Comment by rgommers** [comment]
@joelachance is that the inverse of this arrow?

<img width="390" alt="image" src="https://user-images.githubusercontent.com/98330/71770113-71585380-2f29-11ea-8c7e-fafc01d052aa.png">

Perhaps with getting rid of some of the superfluous whitespace, there's not much left to do here?

**Comment by joelachance** [comment]
I'll direct this one to @InessaPawson. I believe she wanted an arrow above the fold to indicate there is additional content below. Not related to the arrow that appears bottom right when you scroll down.

**Comment by InessaPawson** [comment]
@rgommers @joelachance 
Indeed, the idea is to add a scroll down arrow to the homepage to indicate to the users that there is more (and valuable!) information if you scroll down. 

Some UX experts argue that using scroll arrows is bad practice since you need to explain your design. While others believe that everyone scrolls anyways, and advise not to bother much with content visibility layout. 

As an alternative to the scroll down arrow, the next content block could be partially visible below the displayed one, prompting a user to keep scrolling. I prefer segmenting information visually and don’t see anything wrong with arrows.

**Comment by InessaPawson** [comment]
To make sure that we are all on the same page, the new numpy.org homepage consists of the four content blocks: interactive shell, ‘In a nutshell’, ‘Case studies’, ’Ecosystem’, footer.

**Comment by rgommers** [comment]
> As an alternative to the scroll down arrow, the next content block could be partially visible below the displayed one, prompting a user to keep scrolling. I prefer segmenting information visually and don’t see anything wrong with arrows.

I think that the amount of whitespace will be reduced, while keeping the segmentation into section. I suspect with reduced whitespace it's unlikely not to see that there a next section, so this is probably unnecessary. I'd suggest to leave this issue open for now, but it looks low prio compared to most other issues.

**Comment by rgommers** [comment]
> To make sure that we are all on the same page, the new numpy.org homepage consists of the four content blocks: interactive shell, ‘In a nutshell’, ‘Case studies’, ’Ecosystem’.

agreed:)

**Comment by joelachance** [comment]
The 'Key Features' section is now visible above the fold. Closing ticket.
