### ISSUE TITLE
#Copy: Suggested Copy Improvisations for landing page

### ISSUE THREAD

**Issue by shaloo** [numpy/numpy.org#93]
@rgommers, @joelachance - Please review and let me know if this copy is better than what currently exists on the landing page. This is a mock up in powerpoint - needs to be translated into html/md - Hugo way - if okayed. Hence this ticket. Not sure if someone is already working on it, if not, I can process this.

<img width="1174" alt="copy-improv-landing" src="https://user-images.githubusercontent.com/5890484/69944734-0244a500-150e-11ea-9877-68a564bd6180.png">

**Comment by rgommers** [comment]
I think the textual tweak (start with "fast" under "Powerful N-dim ...", and the text under "Interoperable")  are improvements. I don't think I'm a fan of the gray highlights, since the 1-2 sentences aren't really in need of a summary and it may even be misleading (e.g. the essence of open source isn't "free to use").

So perhaps you can open a PR for just the textual changes?

**Comment by shaloo** [comment]
Alright, sounds good.

**Comment by shaloo** [comment]
PR https://github.com/numpy/numpy.org/pull/105 submitted with suggested changes.
